dashboard/urls.py
from django.urls import path
from . import views


app_name = 'dashboard'
urlpatterns = [
    path('', views.FeedView.as_view(), name='feed'),
    path('group/', views.GroupView.as_view(), name='group'),
]

ihc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('music/', include('music.urls')),
    path('search/', include('search.url')),
]

music/urls.py
from django.urls import path
from . import views

app_name = 'music'
urlpatterns = [
    path('my_music/', views.MyMusicView.as_view(), name='my_music'),
    path('discover/', views.DiscoverView.as_view(), name='discover'),
    path('detail_music/', views.DetailMusicView.as_view(), name='detail_music'),
    path('detail_album/', views.DetailAlbumView.as_view(), name='detail_album'),
    path('detail_playlist/', views.DetailPlaylistView.as_view(), name='detail_playlist'),
]

music/views.py
from django.views.generic.base import TemplateView
from dashboard.views import FeedView

class MyMusicView(TemplateView):
    template_name = "music/my_music.html"


class DiscoverView(TemplateView):
    template_name = "music/discover.html"


class DetailMusicView(TemplateView):
    template_name = "music/detail_music.html"


class DetailAlbumView(TemplateView):
    template_name = "music/detail_album.html"


class DetailPlaylistView(TemplateView):
    template_name = "music/detail_playlist.html"

music/templates/music/album_item.html
<div id="album" class="col-xs-2 col-sm-2 col-md-2 float-left">

  <div class="album-item">
    <img class="img-fluid card-img-top" src={{image}}>
    <a id="album-play-{{num}}" href="#" class="slider_info">
      <i class="fas fa-play fa-3x play-button"></i>
    </a>
    <div class="album-info"> Lemonade <br> Beyoncé </div>
  </div>

  <div id="album-options" class="float-right">
    <a class="add" href="{% url 'music:my_music' %}">
      {% if request.resolver_match.url_name == "discover" %}
        <i class="fas fa-plus-circle float-left mr-1"></i>
        <span>Adicionar</span>
      {% else %}
        <i class="fas fa-trash-alt float-left mr-1"></i>
        <span>Remover</span>
      {% endif %}
    </a>
    {% if num < 11  %}
      <a class="details" href="{% url 'music:detail_music'%}">
        <i class="fas fa-external-link-square-alt float-left mr-1"></i>
        <span>Detalhes</span>
      </a>
    {% else %}
      <a class="details" href="{% url 'music:detail_album'%}">
        <i class="fas fa-external-link-square-alt float-left mr-1"></i>
        <span>Detalhes</span>
      </a>
    {% endif %}
  </div>

</div>

music/templates/music/detail_album.html
{% extends 'core/base.html' %}
{% load static %}

{% block navbar %}
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link ml-5" href="{% url 'dashboard:feed' %}">Dashboard</a>
      <a class="nav-item nav-link" href="{% url 'music:discover' %}">Músicas</a>
    </div>
  </div>
{% endblock navbar%}

{% block css %}
  <link href="{% static 'music/css/detail_music.css' %}" rel="stylesheet">
  <link href="{% static 'music/css/detail_album.css' %}" rel="stylesheet">
  <link href="{% static 'dashboard/css/feed.css' %}" rel="stylesheet">
{% endblock css%}

{% block content %}
  <div id="album-cover">
    <img class="img-fluid" src="https://upload.wikimedia.org/wikipedia/pt/thumb/a/ae/Shawn_Mendes_album.jpg/220px-Shawn_Mendes_album.jpg">
  </div>

  <div class="music_info">
    <p class="artist">SHAWN MENDES</p>
    <p class="title">Shawn Mendes</p>
    <hr class="hr-style">
    <fieldset class="rating">
      <input type="radio" id="star5" name="rating" value="5" /><label class ="full" for="star5" title="Awesome - 5 stars"></label>
      <input type="radio" id="star4half" name="rating" value="4 and a half" /><label class="half" for="star4half" title="Pretty good - 4.5 stars"></label>
      <input type="radio" id="star4" name="rating" value="4" /><label class = "full" for="star4" title="Pretty good - 4 stars"></label>
      <input type="radio" id="star3half" name="rating" value="3 and a half" /><label class="half" for="star3half" title="Meh - 3.5 stars"></label>
      <input type="radio" id="star3" name="rating" value="3" /><label class = "full" for="star3" title="Meh - 3 stars"></label>
      <input type="radio" id="star2half" name="rating" value="2 and a half" /><label class="half" for="star2half" title="Kinda bad - 2.5 stars"></label>
      <input type="radio" id="star2" name="rating" value="2" /><label class = "full" for="star2" title="Kinda bad - 2 stars"></label>
      <input type="radio" id="star1half" name="rating" value="1 and a half" /><label class="half" for="star1half" title="Meh - 1.5 stars"></label>
      <input type="radio" id="star1" name="rating" value="1" /><label class = "full" for="star1" title="Sucks big time - 1 star"></label>
      <input type="radio" id="starhalf" name="rating" value="half" /><label class="half" for="starhalf" title="Sucks big time - 0.5 stars"></label>
    </fieldset>
    <div class="share">
      <p>Compartilhar avaliação:</p>
      <i class="fab fa-facebook fa-2x"></i>
      <i class="fab fa-twitter-square fa-2x"></i>
    </div>
  </div>

  <ol id="playlist">
    <li><a class="track" href="#">Searching (Memoirs Of A New Discovery)</a> <span class="time">2:54</span></li>
    <li><a class="track" href="#">Charade (Exploring The Surface) feat. Julie Thurman</a> <span class="time">3:04</span></li>
    <li><a class="track" href="#">Speed of Sound (An Interruption In Spaceflight)</a> <span class="time">5:05</span></li>
    <li><a class="track" href="#">Searching (Memoirs Of A New Discovery)</a> <span class="time">2:54</span></li>
    <li><a class="track" href="#">Charade (Exploring The Surface) feat. Julie Thurman</a> <span class="time">3:04</span></li>
    <li><a class="track" href="#">Speed of Sound (An Interruption In Spaceflight)</a> <span class="time">5:05</span></li>
  </ol>


      <div class="row align-items-center justify-content-center">
      <div class="col-7">

    <div class="card my-1 content-card">
      <div class="card-header pt-1 pb-0 content-card-header">

        <div class="row">
          <div class="col-auto pt-1">
            <img src="{% static 'core/img/user11.png' %}" class="img-circle small-profile-img">
          </div>
          <div class="col">
            <p class="black-text font-weight-bold row my-0"> Xacrinha Xiscrane </p>
            <p class="black-text font-weight-light font-italic row my-0">14 de maio de 2019</p>
          </div>
        </div>
      
      </div>

    <div class="card-body content-card-body">

        <div class="row px-2">
        <p class="black-text card-text">Aí não sei, não sou criativa.</p>
        </div>


      </div>

      <div class="card-footer text-muted content-card-footer">
        <div class="row align-items-center">
          <div class="col">

            {% include "dashboard/content_footer.html" with content_piece=content_piece%}

          </div>
        </div>
      </div>
    </div>
    </div>

    </div>

{% endblock content%}

{% block js %}
  <script type="text/javascript" src="{% static 'core/js/player.js' %}"></script>
  <script type="text/javascript" src="{% static 'music/js/album_play.js' %}"></script>
{%  endblock js %}

music/templates/music/discover.html
{% extends 'core/base.html' %}
{% load static %}

{% block navbar %}
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link ml-5" href="{% url 'dashboard:feed' %}">Dashboard</a>
      <a class="nav-item nav-link selected" href="#">Músicas</a>
    </div>
  </div>
{% endblock navbar%}

{% block css %}
  <link href="{% static 'music/css/my_music.css' %}" rel="stylesheet">
{% endblock css%}

{% block content %}

  <div class="mt-3 mr-5 float-right page-switch">
    <a href="{% url 'music:discover'%}" class="mr-3 current">Descobrir</a>
    <a href="{% url 'music:my_music'%}" class="mr-1">Minhas Músicas</a>
  </div>

  <h3 class="mt-5">Playlists dos seus amigos</h3>

  <div class="container">
    <div id="demo" class="carousel slide" data-ride="carousel" data-interval="false">
      <!-- The slideshow -->
      <div class="carousel-inner no-padding my-5">

        <div class="carousel-item">
          {% include "music/playlist_item.html" with num=22 image="https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Beyonce_-_Lemonade_%28Official_Album_Cover%29.png/220px-Beyonce_-_Lemonade_%28Official_Album_Cover%29.png" %}
          {% include "music/playlist_item.html" with num=23 image="https://upload.wikimedia.org/wikipedia/pt/thumb/8/86/Capa_de_V_%28Maroon_5%29.png/220px-Capa_de_V_%28Maroon_5%29.png" %}
          {% include "music/playlist_item.html" with num=24 image="https://upload.wikimedia.org/wikipedia/en/thumb/a/a0/DNCE_-_SWAAY_%28Album_Cover%29.png/220px-DNCE_-_SWAAY_%28Album_Cover%29.png"%}
          {% include "music/playlist_item.html" with num=26 image="https://upload.wikimedia.org/wikipedia/en/f/fd/Lady_Gaga_-_Joanne_%28Official_Album_Cover%29.png" %}
          {% include "music/playlist_item.html" with num=25 image="https://images-na.ssl-images-amazon.com/images/I/91C3krr3q-L._SX425_.jpg" %}
          </div>

        <div class="carousel-item active">
          {% include "music/playlist_item.html" with num=17 image="https://images-na.ssl-images-amazon.com/images/I/91C3krr3q-L._SX425_.jpg" %}
          {% include "music/playlist_item.html" with num=19 image="https://upload.wikimedia.org/wikipedia/pt/thumb/a/ae/Shawn_Mendes_album.jpg/220px-Shawn_Mendes_album.jpg" %}
          {% include "music/playlist_item.html" with num=18 image="https://upload.wikimedia.org/wikipedia/en/thumb/d/d5/Ariana_Grande_My_Everything_2014_album_artwork.png/220px-Ariana_Grande_My_Everything_2014_album_artwork.png" %}
          {% include "music/playlist_item.html" with num=20 image="https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Halsey_-_Badlands.png/220px-Halsey_-_Badlands.png" %}
          {% include "music/playlist_item.html" with num=21 image="https://upload.wikimedia.org/wikipedia/en/f/fd/Lady_Gaga_-_Joanne_%28Official_Album_Cover%29.png" %}
        </div>

      </div>

      <!-- Left and right controls -->
      <a class="carousel-control-prev" href="#demo" data-slide="prev">
         <span class="carousel-control-prev-icon sp"></span>
        <span class="sr-only">Anterior</span>
      </a>
      <a class="carousel-control-next" href="#demo" data-slide="next">
        <span class="carousel-control-next-icon sp"></span>
        <span class="sr-only">Próximo</span>
      </a>

    </div>
  </div>

  <h3>Novidades: Músicas</h3>

  <div class="container">
    <div id="demo2" class="carousel slide" data-ride="carousel" data-interval="false">
      <!-- The slideshow -->
      <div class="carousel-inner no-padding my-5">

        <div class="carousel-item ">
          {% include "music/album_item.html" with num=1 image="https://upload.wikimedia.org/wikipedia/pt/thumb/c/c3/1989_de_Taylor_Swift.jpg/220px-1989_de_Taylor_Swift.jpg"%}
          {% include "music/album_item.html" with num=2 image="https://images.genius.com/565381daa3a7d73a551d9738732b26d5.1000x1000x1.jpg" %}
          {% include "music/album_item.html" with num=3 image="https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Beyonce_-_Lemonade_%28Official_Album_Cover%29.png/220px-Beyonce_-_Lemonade_%28Official_Album_Cover%29.png" %}
          {% include "music/album_item.html" with num=4 image="https://upload.wikimedia.org/wikipedia/pt/thumb/8/86/Capa_de_V_%28Maroon_5%29.png/220px-Capa_de_V_%28Maroon_5%29.png" %}
          {% include "music/album_item.html" with num=5 image="https://upload.wikimedia.org/wikipedia/en/thumb/a/a0/DNCE_-_SWAAY_%28Album_Cover%29.png/220px-DNCE_-_SWAAY_%28Album_Cover%29.png"%}
        </div>

        <div class="carousel-item active">
          {% include "music/album_item.html" with num=6 image="https://upload.wikimedia.org/wikipedia/en/f/fd/Lady_Gaga_-_Joanne_%28Official_Album_Cover%29.png" %}
          {% include "music/album_item.html" with num=7 image="https://images-na.ssl-images-amazon.com/images/I/91C3krr3q-L._SX425_.jpg" %}
          {% include "music/album_item.html" with num=8 image="https://upload.wikimedia.org/wikipedia/pt/thumb/a/ae/Shawn_Mendes_album.jpg/220px-Shawn_Mendes_album.jpg" %}
          {% include "music/album_item.html" with num=9 image="https://upload.wikimedia.org/wikipedia/en/thumb/d/d5/Ariana_Grande_My_Everything_2014_album_artwork.png/220px-Ariana_Grande_My_Everything_2014_album_artwork.png" %}
          {% include "music/album_item.html" with num=10 image="https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Halsey_-_Badlands.png/220px-Halsey_-_Badlands.png" %}

        </div>
      </div>

      <!-- Left and right controls -->
      <a class="carousel-control-prev" href="#demo2" data-slide="prev">
         <span class="carousel-control-prev-icon sp"></span>
        <span class="sr-only">Anterior</span>
      </a>
      <a class="carousel-control-next" href="#demo2" data-slide="next">
        <span class="carousel-control-next-icon sp"></span>
        <span class="sr-only">Próximo</span>
      </a>

    </div>
  </div>

  <h3>Novidades: Álbuns </h3>

  <div class="container">
    <div id="demo3" class="carousel slide" data-ride="carousel" data-interval="false">
      <!-- The slideshow -->
      <div class="carousel-inner no-padding my-5">

        <div class="carousel-item active">
          {% include "music/album_item.html" with num=21 image="https://upload.wikimedia.org/wikipedia/pt/thumb/a/ae/Shawn_Mendes_album.jpg/220px-Shawn_Mendes_album.jpg" %}
          {% include "music/album_item.html" with num=22 image="https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Halsey_-_Badlands.png/220px-Halsey_-_Badlands.png" %}
          {% include "music/album_item.html" with num=23 image="https://upload.wikimedia.org/wikipedia/pt/thumb/c/c3/1989_de_Taylor_Swift.jpg/220px-1989_de_Taylor_Swift.jpg"%}
          {% include "music/album_item.html" with num=24 image="https://images.genius.com/565381daa3a7d73a551d9738732b26d5.1000x1000x1.jpg" %}
          {% include "music/album_item.html" with num=25 image="https://upload.wikimedia.org/wikipedia/en/thumb/d/d5/Ariana_Grande_My_Everything_2014_album_artwork.png/220px-Ariana_Grande_My_Everything_2014_album_artwork.png" %}
        </div>

        <div class="carousel-item">
          {% include "music/album_item.html" with num=26 image="https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Beyonce_-_Lemonade_%28Official_Album_Cover%29.png/220px-Beyonce_-_Lemonade_%28Official_Album_Cover%29.png" %}
          {% include "music/album_item.html" with num=27 image="https://upload.wikimedia.org/wikipedia/pt/thumb/8/86/Capa_de_V_%28Maroon_5%29.png/220px-Capa_de_V_%28Maroon_5%29.png" %}
          {% include "music/album_item.html" with num=28 image="https://upload.wikimedia.org/wikipedia/en/thumb/a/a0/DNCE_-_SWAAY_%28Album_Cover%29.png/220px-DNCE_-_SWAAY_%28Album_Cover%29.png"%}
          {% include "music/album_item.html" with num=29 image="https://upload.wikimedia.org/wikipedia/en/f/fd/Lady_Gaga_-_Joanne_%28Official_Album_Cover%29.png" %}
          {% include "music/album_item.html" with num=30 image="https://images-na.ssl-images-amazon.com/images/I/91C3krr3q-L._SX425_.jpg" %}
        </div>
      </div>

      <!-- Left and right controls -->
      <a class="carousel-control-prev" href="#demo3" data-slide="prev">
         <span class="carousel-control-prev-icon sp"></span>
        <span class="sr-only">Anterior</span>
      </a>
      <a class="carousel-control-next" href="#demo3" data-slide="next">
        <span class="carousel-control-next-icon sp"></span>
        <span class="sr-only">Próximo</span>
      </a>

    </div>
  </div>
{% endblock content%}

{% block js %}
  <script type="text/javascript" src="{% static 'core/js/player.js' %}"></script>
  <script type="text/javascript" src="{% static 'music/js/album_play.js' %}"></script>
{%  endblock js %}

music/templates/music/my_music.html
{% extends 'core/base.html' %}
{% load static %}

{% block navbar %}
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link ml-5" href="{% url 'dashboard:feed' %}">Dashboard</a>
      <a class="nav-item nav-link selected" href="#">Músicas</a>
    </div>
  </div>
{% endblock navbar%}

{% block css %}
  <link href="{% static 'music/css/my_music.css' %}" rel="stylesheet">
{% endblock css%}

{% block content %}

  <div class="mt-3 mr-5 float-right page-switch">
        <a href="{% url 'music:discover'%}" class="mr-3">Descobrir</a>
    <a href="{% url 'music:my_music'%}" class="mr-1 current">Minhas Músicas</a>
  </div>

  <h3 class="mt-5">Minhas Playlists</h3>

  <div class="container">
    <div id="demo" class="carousel slide" data-ride="carousel" data-interval="false">
      <!-- The slideshow -->
      <div class="carousel-inner no-padding my-5">

        <div class="carousel-item active">
          {% include "music/playlist_item.html" with num=22 image="https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Beyonce_-_Lemonade_%28Official_Album_Cover%29.png/220px-Beyonce_-_Lemonade_%28Official_Album_Cover%29.png" %}
          {% include "music/playlist_item.html" with num=23 image="https://upload.wikimedia.org/wikipedia/pt/thumb/8/86/Capa_de_V_%28Maroon_5%29.png/220px-Capa_de_V_%28Maroon_5%29.png" %}
          {% include "music/playlist_item.html" with num=24 image="https://upload.wikimedia.org/wikipedia/en/thumb/a/a0/DNCE_-_SWAAY_%28Album_Cover%29.png/220px-DNCE_-_SWAAY_%28Album_Cover%29.png"%}
          {% include "music/playlist_item.html" with num=26 image="https://upload.wikimedia.org/wikipedia/en/f/fd/Lady_Gaga_-_Joanne_%28Official_Album_Cover%29.png" %}
          {% include "music/playlist_item.html" with num=25 image="https://images-na.ssl-images-amazon.com/images/I/91C3krr3q-L._SX425_.jpg" %}
          </div>

        <div class="carousel-item">
          {% include "music/playlist_item.html" with num=17 image="https://images-na.ssl-images-amazon.com/images/I/91C3krr3q-L._SX425_.jpg" %}
          {% include "music/playlist_item.html" with num=19 image="https://upload.wikimedia.org/wikipedia/pt/thumb/a/ae/Shawn_Mendes_album.jpg/220px-Shawn_Mendes_album.jpg" %}
          {% include "music/playlist_item.html" with num=18 image="https://upload.wikimedia.org/wikipedia/en/thumb/d/d5/Ariana_Grande_My_Everything_2014_album_artwork.png/220px-Ariana_Grande_My_Everything_2014_album_artwork.png" %}
          {% include "music/playlist_item.html" with num=20 image="https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Halsey_-_Badlands.png/220px-Halsey_-_Badlands.png" %}
          {% include "music/playlist_item.html" with num=21 image="https://upload.wikimedia.org/wikipedia/en/f/fd/Lady_Gaga_-_Joanne_%28Official_Album_Cover%29.png" %}
        </div>

      </div>

      <!-- Left and right controls -->
      <a class="carousel-control-prev" href="#demo" data-slide="prev">
         <span class="carousel-control-prev-icon sp"></span>
        <span class="sr-only">Anterior</span>
      </a>
      <a class="carousel-control-next" href="#demo" data-slide="next">
        <span class="carousel-control-next-icon sp"></span>
        <span class="sr-only">Próximo</span>
      </a>

    </div>
  </div>

  <h3>Minhas Músicas</h3>

  <div class="container">
    <div id="demo3" class="carousel slide" data-ride="carousel" data-interval="false">
      <!-- The slideshow -->
      <div class="carousel-inner no-padding my-5">

        <div class="carousel-item active">
          {% include "music/album_item.html" with num=1 image="https://upload.wikimedia.org/wikipedia/en/f/fd/Lady_Gaga_-_Joanne_%28Official_Album_Cover%29.png" %}
          {% include "music/album_item.html" with num=2 image="https://images-na.ssl-images-amazon.com/images/I/91C3krr3q-L._SX425_.jpg" %}
          {% include "music/album_item.html" with num=3 image="https://upload.wikimedia.org/wikipedia/pt/thumb/a/ae/Shawn_Mendes_album.jpg/220px-Shawn_Mendes_album.jpg" %}
          {% include "music/album_item.html" with num=4 image="https://upload.wikimedia.org/wikipedia/en/thumb/d/d5/Ariana_Grande_My_Everything_2014_album_artwork.png/220px-Ariana_Grande_My_Everything_2014_album_artwork.png" %}
          {% include "music/album_item.html" with num=5 image="https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Halsey_-_Badlands.png/220px-Halsey_-_Badlands.png" %}
        </div>

        <div class="carousel-item">
          {% include "music/album_item.html" with num=6 image="https://upload.wikimedia.org/wikipedia/pt/thumb/c/c3/1989_de_Taylor_Swift.jpg/220px-1989_de_Taylor_Swift.jpg"%}
          {% include "music/album_item.html" with num=7 image="https://images.genius.com/565381daa3a7d73a551d9738732b26d5.1000x1000x1.jpg" %}
          {% include "music/album_item.html" with num=8 image="https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Beyonce_-_Lemonade_%28Official_Album_Cover%29.png/220px-Beyonce_-_Lemonade_%28Official_Album_Cover%29.png" %}
          {% include "music/album_item.html" with num=9 image="https://upload.wikimedia.org/wikipedia/pt/thumb/8/86/Capa_de_V_%28Maroon_5%29.png/220px-Capa_de_V_%28Maroon_5%29.png" %}
          {% include "music/album_item.html" with num=10 image="https://upload.wikimedia.org/wikipedia/en/thumb/a/a0/DNCE_-_SWAAY_%28Album_Cover%29.png/220px-DNCE_-_SWAAY_%28Album_Cover%29.png"%}
        </div>

      </div>

      <!-- Left and right controls -->
      <a class="carousel-control-prev" href="#demo3" data-slide="prev">
         <span class="carousel-control-prev-icon sp"></span>
        <span class="sr-only">Anterior</span>
      </a>
      <a class="carousel-control-next" href="#demo3" data-slide="next">
        <span class="carousel-control-next-icon sp"></span>
        <span class="sr-only">Próximo</span>
      </a>

    </div>
  </div>

  <h3>Meus Álbuns</h3>

  <div class="container">
    <div id="demo2" class="carousel slide" data-ride="carousel" data-interval="false">
      <!-- The slideshow -->
      <div class="carousel-inner no-padding my-5">

        <div class="carousel-item">
          {% include "music/album_item.html" with num=14 image="https://upload.wikimedia.org/wikipedia/en/thumb/d/d5/Ariana_Grande_My_Everything_2014_album_artwork.png/220px-Ariana_Grande_My_Everything_2014_album_artwork.png" %}
          {% include "music/album_item.html" with num=15 image="https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Halsey_-_Badlands.png/220px-Halsey_-_Badlands.png" %}
          {% include "music/album_item.html" with num=11 image="https://upload.wikimedia.org/wikipedia/en/f/fd/Lady_Gaga_-_Joanne_%28Official_Album_Cover%29.png" %}
          {% include "music/album_item.html" with num=13 image="https://upload.wikimedia.org/wikipedia/pt/thumb/a/ae/Shawn_Mendes_album.jpg/220px-Shawn_Mendes_album.jpg" %}
          {% include "music/album_item.html" with num=12 image="https://images-na.ssl-images-amazon.com/images/I/91C3krr3q-L._SX425_.jpg" %}
        </div>

        <div class="carousel-item active">
          {% include "music/album_item.html" with num=19 image="https://upload.wikimedia.org/wikipedia/pt/thumb/8/86/Capa_de_V_%28Maroon_5%29.png/220px-Capa_de_V_%28Maroon_5%29.png" %}
          {% include "music/album_item.html" with num=20 image="https://upload.wikimedia.org/wikipedia/en/thumb/a/a0/DNCE_-_SWAAY_%28Album_Cover%29.png/220px-DNCE_-_SWAAY_%28Album_Cover%29.png"%}
          {% include "music/album_item.html" with num=17 image="https://images.genius.com/565381daa3a7d73a551d9738732b26d5.1000x1000x1.jpg" %}
          {% include "music/album_item.html" with num=18 image="https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Beyonce_-_Lemonade_%28Official_Album_Cover%29.png/220px-Beyonce_-_Lemonade_%28Official_Album_Cover%29.png" %}
          {% include "music/album_item.html" with num=16 image="https://upload.wikimedia.org/wikipedia/pt/thumb/c/c3/1989_de_Taylor_Swift.jpg/220px-1989_de_Taylor_Swift.jpg"%}
        </div>

      </div>

      <!-- Left and right controls -->
      <a class="carousel-control-prev" href="#demo2" data-slide="prev">
         <span class="carousel-control-prev-icon sp"></span>
        <span class="sr-only">Anterior</span>
      </a>
      <a class="carousel-control-next" href="#demo2" data-slide="next">
        <span class="carousel-control-next-icon sp"></span>
        <span class="sr-only">Próximo</span>
      </a>

    </div>
  </div>


{% endblock content%}

{% block js %}
  <script type="text/javascript" src="{% static 'core/js/player.js' %}"></script>
  <script type="text/javascript" src="{% static 'music/js/album_play.js' %}"></script>
{%  endblock js %}