account/urls.py
from django.urls import path, include
from . import views

app_name = 'account'
urlpatterns = [
    path('', views.SignInView.as_view(), name='sign_in'),
    path('sign_up/', views.SignUpView.as_view(), name='sign_up'),
    path('help_page/', views.HelpPage.as_view(), name='help_page'),
    path('instruction/', views.InstructionPage.as_view(), name='instruction_page'),
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #path('', views.SignInView.as_view(), name='sign_in'),
    #path('sign_up/', views.SignUpView.as_view(), name='sign_up'),
]

ihc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('music/', include('music.urls')),
    path('search/', include('search.url')),
]

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt_BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}BeatClan{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="IHC">

    <!--Icons-->
    <!--<link rel="icon" href="{% static 'core/images/favicon.ico' %}">-->
    <!--<link rel="shortcut icon" href="{% static 'core/images/favicon.ico' %}">-->

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block bootstrap %}

      <!-- CSS  -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

      <!-- JS-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

      <!-- Custom fonts for this template -->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
      <link href="{% static 'core/css/core.css' %}" rel="stylesheet">
    {% endblock bootstrap%}

    {% block css %}
      <!-- Custom CSS-->
    {% endblock css %}

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg fixed-top primary-color">

      <img src="{% static 'core/img/BC.png' %}" width="40px" alt="">

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      {% block navbar %}

      {% endblock navbar %}

      <i class="fas fa-step-backward"></i>
      <a id="play-icon" href="javascript:void(0)" rel="me">
        <i class="fas fa-play mb-1 ml-4"></i>
      </a>
      <i class="fas fa-step-forward" ></i>


      <div class="audio-player">
        <div class="audio-wrapper" id="player-container" href="javascript:;">
          <audio id="player" ontimeupdate="initProgressBar()">
            <source src="http://www.music.helsinki.fi/tmt/opetus/uusmedia/esim/a2002011001-e02.wav" type="audio/mp3">
          </audio>
        </div>
        <div class="player-bar">
          <span id="seekObjContainer">
            <progress id="seekObj" value="0" max="1"></progress>
          </span>
          <br>
          <!--<small style="float: left; position: relative; left: 15px;" class="start-time"></small>-->
          <!--<small style="float: right; position: relative; right: 20px;" class="end-time"></small>-->
        </div>
      </div>

      <div class="dropdown show">
        <a href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class=" fas fa-chevron-down mr-5"></i>
        </a>

        <div class="dropdown-menu player-drop" aria-labelledby="dropdownMenuLink">
          <img class="img-fluid card-img-top" src="https://images.genius.com/565381daa3a7d73a551d9738732b26d5.1000x1000x1.jpg">
          <p>Starboy<br>The Weeknd</p>
          <i class="fas fa-random"></i>
          <i class="fas fa-redo-alt"></i>
        </div>
      </div>

      <a class="search" href="{% url 'search:first_page_search' %}"><i class="fas fa-search"></i></a>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-bell"></i></a>
          <ul class="dropdown-menu notify-drop dropdown-menu-right">
            <div class="notify-drop-title">
            	<div class="row">
            		<div class="col-md-6 col-sm-6 col-xs-6">Notificações (<b>2</b>)</div>
            		<div class="col-md-6 col-sm-6 col-xs-6 text-right"><a href="" class="rIcon allRead" data-tooltip="tooltip" data-placement="bottom" title="tümü okundu."></i></a></div>
            	</div>
            </div>
            <!-- end notify title -->
            <!-- notify content -->
            <div class="drop-content">

              <li>
                <a href="">
            		  <div class="notification-item">
                    <img class="float-left" src="http://placehold.it/45x45" alt="">
                    <p class="float-left">Lorem ipsum sit dolor amet consilium.</p>
                  </div>
                </a>
            	</li>

              <li>
                <a href="">
            		  <div class="notification-item">
                    <img class="float-left" src="http://placehold.it/45x45" alt="">
                    <p class="float-left">Lorem ipsum sit dolor amet consilium.</p>
                  </div>
                </a>
            	</li>

               <li>
                <a href="">
            		  <div class="notification-item">
                    <img class="float-left" src="http://placehold.it/45x45" alt="">
                    <p class="float-left">Lorem ipsum sit dolor amet consilium.</p>
                  </div>
                </a>
            	</li>

               <li>
                <a href="">
            		  <div class="notification-item">
                    <img class="float-left" src="http://placehold.it/45x45" alt="">
                    <p class="float-left">Lorem ipsum sit dolor amet consilium.</p>
                  </div>
                </a>
            	</li>

               <li>
                <a href="">
            		  <div class="notification-item">
                    <img class="float-left" src="http://placehold.it/45x45" alt="">
                    <p class="float-left">Lorem ipsum sit dolor amet consilium.</p>
                  </div>
                </a>
            	</li>

               <li>
                <a href="">
            		  <div class="notification-item">
                    <img class="float-left" src="http://placehold.it/45x45" alt="">
                    <p class="float-left">Lorem ipsum sit dolor amet consilium.</p>
                  </div>
                </a>
            	</li>

            </div>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown"><a href="#" data-toggle="dropdown"><i class="fas fa-user-circle"></i></a>
          <ul class="dropdown-menu dropdown-menu-right">
            <li>
              <div class="navbar-content">
                <div class="row">
                  <div class="col-md-5">
                    <img src="http://placehold.it/120x120" alt="Alternate Text" class="img-responsive" />
                    <p class="text-center small ml-3">
                      <a class="grey-link" href="#">Trocar foto</a>
                    </p>
                  </div>
                  <div class="col-md-7">
                    <span>Shimira</span>
                    <p class="text-muted small">shimira@gmail.com</p>
                    <div class="divider"></div>
                    <a href="#" class="grey-link" >Ver Perfil</a>
                  </div>
                </div>
              </div>
              <div class="navbar-footer">
                <div class="navbar-footer-content">
                  <div class="row">
                    <div class="col-md-6">
                      <a href="#" class="red-link ml-3" >Trocar senha</a>
                    </div>
                    <div class="col-md-6">
                      <a href="{% url 'account:sign_in'%}" class="red-link pull-right ml-5">Sair</a>
                    </div>
                  </div>
                </div>
              </div>
            </li>
          </ul>
        </li>
      </ul>

    </nav>


    <!-- Page Content -->
    <wrapper class="d-flex flex-column">

      <!-- Content -->
      <div class="flex-fill out-sidebar-content mt-5">
        {% block content %}
        {% endblock content %}
      </div>

      <!-- Footer -->
      <div class="copyright py-4 text-center text-white">
        <div class="container">
          <small>Copyright &copy; BeatClan 2018</small>
        </div>
      </div>
    </wrapper>
    </div>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-to-top d-lg-none position-fixed ">
      <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
        <i class="fa fa-chevron-up"></i>
      </a>
    </div>

    <!-- Placed at the end of the document so the pages load faster -->
    {% block js %}
     <script type="text/javascript" src="{% static 'core/js/player.js' %}"></script>
    {%  endblock js %}

  </body>
</html>