dashboard/urls.py
from django.urls import path
from . import views


app_name = 'dashboard'
urlpatterns = [
    path('', views.FeedView.as_view(), name='feed'),
    path('group/', views.GroupView.as_view(), name='group'),
]

ihc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('music/', include('music.urls')),
    path('search/', include('search.url')),
]

music/urls.py
from django.urls import path
from . import views

app_name = 'music'
urlpatterns = [
    path('my_music/', views.MyMusicView.as_view(), name='my_music'),
    path('discover/', views.DiscoverView.as_view(), name='discover'),
    path('detail_music/', views.DetailMusicView.as_view(), name='detail_music'),
    path('detail_album/', views.DetailAlbumView.as_view(), name='detail_album'),
    path('detail_playlist/', views.DetailPlaylistView.as_view(), name='detail_playlist'),
]

dashboard/views.py
from django.views.generic.base import TemplateView
from django.templatetags.static import static
from random import choice, sample, shuffle, randint


class FeedView(TemplateView):
    template_name = "dashboard/feed.html"

    CONTENT_MUSIC = 'cm'
    CONTENT_VIDEO = 'cv'
    # there is no content type for text, because all
    # posts can have text
    CONTENT_PHOTO = 'cph'
    CONTENT_PLAYLIST = 'cpl'

    content_types = [
        CONTENT_MUSIC,
        CONTENT_PLAYLIST,
        CONTENT_VIDEO,
        CONTENT_PHOTO,
    ]

    musics = [
        {
            'music_name': 'Diamond Heart',
            'music_author': 'Lady Gaga',
            'music_album' : 'Joane',
            'music_image_link':  static('core/img/album1.png'),
        },
        {
            'music_name': 'American Teen',
            'music_author': 'Khalid',
            'music_album' : 'American Teen',
            'music_image_link':  static('core/img/album2.jpg'),
        },
        {
            'music_name': 'In My Blood',
            'music_author': 'Shawn Mendes',
            'music_album' : 'Shawn Mendes',
            'music_image_link':  static('core/img/album3.jpg'),
        },
        {
            'music_name': 'One Last Time',
            'music_author': 'Ariana Grande',
            'music_album' : 'My Everything',
            'music_image_link':  static('core/img/album4.png'),
        },
        {
            'music_name': 'Hold Me Down',
            'music_author': 'Halsey',
            'music_album' : 'Badlands',
            'music_image_link':  static('core/img/album5.png'),
        },
        {
            'music_name': 'Shake It Off',
            'music_author': 'Taylor Swift',
            'music_album' : '1989',
            'music_image_link':  static('core/img/album6.jpg'),
        },
        {
            'music_name': 'Die for You',
            'music_author': 'The Weeknd',
            'music_album' : 'Starboy',
            'music_image_link':  static('core/img/album7.jpg'),
        },
        {
            'music_name': 'Hold Up',
            'music_author': 'Beyonce',
            'music_album' : 'Lemonade',
            'music_image_link':  static('core/img/album8.png'),
        },
        {
            'music_name': 'Sugar',
            'music_author': 'Maroon 5',
            'music_album' : 'V',
            'music_image_link':  static('core/img/album9.png'),
        },
        {
            'music_name': 'Cake by the Ocean',
            'music_author': 'DNCE',
            'music_album' : 'Swaay',
            'music_image_link':  static('core/img/album10.png'),
        },


    ]

    names = [
        'João Silva',
        'Anthony Manuel Santos',
        'Bernardo Barros',
        'Isis Alves',
        'Luiza Brito',
        'Caroline Oliveira',
        'Joaquim dos Santos',
        'Felipe Bezerra',
        'Haimundo Kosta',
        'Ana Carla',
        'Márcia Fogaça',
        'Laura Lima'
    ]

    imgs = [
        static('core/img/user.png'),
        static('core/img/user1.png'),
        static('core/img/user2.png'),
        static('core/img/user3.png'),
        static('core/img/user4.png'),
        static('core/img/user5.png'),
        static('core/img/user6.png'),
        static('core/img/user7.png'),
        static('core/img/user8.png'),
        static('core/img/user9.png'),
        static('core/img/user10.png'),
        static('core/img/user11.png'),
    ]

    mensages = [
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse pretium tortor purus, sed accumsan dui mattis quis. Aliquam ultrices tempor urna.',
        'Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas placerat nisi quis lacinia tincidunt.',
        'Nullam non nulla eros.',
        'Donec sed ante venenatis, convallis eros finibus, sollicitudin ex. Maecenas elementum lectus nibh, sed ultricies ex pulvinar quis. In hac habitasse platea dictumst.',
        'In varius, tortor eget convallis pretium, ligula est finibus neque, non lacinia purus sapien sodales magna. Nam ultricies condimentum lacus nec tristique. Fusce at nisl eros. Nulla facilisi. ',
        'Ameno, dorime, ameno!',
        'Deus vult!',
        ' Vestibulum ultricies, leo at convallis luctus, urna tellus tempor dolor, eget malesuada metus orci a augue. Fusce gravida, libero ut tristique consectetur, neque dolor molestie elit, in accumsan sem quam quis purus. Nullam dignissim tortor ex, non posuere urna suscipit eu. Sed elementum venenatis diam, at tristique lacus feugiat at. In sit amet tellus vel magna aliquam blandit ultrices vitae felis.',
    ]

    playlist = [
        'Chorar no banho',
        'Só música boa',
        'Rock pesadão',
        'Caminho do trabalho',
        'Só SS',
        'To de férias',
    ]

    @staticmethod
    def get_name():
        return choice(FeedView.names)

    @staticmethod
    def get_comments():

        comments = []

        for i in range(0, choice([0, 0, 0, 1, 1, 2])):
            comments.append(
                {
                    'author': FeedView.get_name(),
                    'img': FeedView.get_img(),
                    'text': FeedView.get_mensage()
                }
            )

        return comments


    @staticmethod
    def get_name_playlist():
        return choice(FeedView.playlist)

    @staticmethod
    def get_img():
        return choice(FeedView.imgs)

    @staticmethod
    def get_mensage():
        return choice(FeedView.mensages)

    @staticmethod
    def get_music():
        return choice(FeedView.musics)

    @staticmethod
    def get_playlist(size):
        return sample(FeedView.musics, size)

    @staticmethod
    def get_chat_friends():

        size = randint(2,10)
        friends = []

        for i in range(0, size):
            friends.append(
                {
                    'img': FeedView.get_img(),
                    'name': FeedView.get_name()
                }
            )

        return friends

    
    @staticmethod
    def get_chat_conversation():

        size = randint(1,4)
        menssages = []

        persons = [
            {
                'img': FeedView.get_img(),
                'type': 'sender'
            },
            {
                'img': FeedView.get_img(),
                'type': 'receiver'
            }
        ]

        for i in range(0, size):
        
            menssages.append(
                {
                    'menssage': FeedView.get_mensage(),
                    'author': choice(persons)
                }
            )
          

        menssages.append(
            {
                'author': persons[0],
                'menssage': FeedView.get_mensage()
            }
        )
        
        menssages.append(
            {
                'author': persons[1],
                'menssage': FeedView.get_mensage()
            }
        )

        return menssages

    @staticmethod
    def get_only_text():
        content_list = []

        for i in range(3, 10):

            content_piece = {
                'author': FeedView.get_name(),
                'author_img': FeedView.get_img(),
                'menssage': FeedView.get_mensage(),
                'date_time': "26 de Abril de 2018 às 16:00h",
                'content_type': 'txt',
                'number_likes' : randint(0,101),
                'comments': FeedView.get_comments()
            }


    def get_random_content(self):
        content_list = []

        for i in range(0, 10):

            random_type = choice(FeedView.content_types)

            content_piece = {
                'author': FeedView.get_name(),
                'author_img': FeedView.get_img(),
                'menssage': FeedView.get_mensage(),
                'date_time': "26 de Abril de 2018 às 16:00h",
                'content_type': random_type,
                'number_likes' : randint(0,101),
                'comments': FeedView.get_comments()
            }

            if random_type is FeedView.CONTENT_MUSIC:
                content_piece.update({'music': FeedView.get_music()})

            if random_type is FeedView.CONTENT_PLAYLIST:
                content_piece.update(
                    {
                        'playlist': FeedView.get_playlist(choice(range(3,len(self.musics))))
                    }
                )







            content_list.append(content_piece)

        return content_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["content"] = self.get_random_content()

        return context

class GroupView(TemplateView):
    template_name = "dashboard/group.html"

    CONTENT_MUSIC = 'cm'
    CONTENT_VIDEO = 'cv'
    # there is no content type for text, because all
    # posts can have text
    CONTENT_PHOTO = 'cph'
    CONTENT_PLAYLIST = 'cpl'

    content_types = [
        CONTENT_MUSIC,
        CONTENT_PLAYLIST,
        CONTENT_VIDEO,
        CONTENT_PHOTO,
    ]

    musics = [
        {
            'music_name': 'Diamond Heart',
            'music_author': 'Lady Gaga',
            'music_album' : 'Joane',
            'music_image_link':  static('core/img/album1.png'),
        },
        {
            'music_name': 'American Teen',
            'music_author': 'Khalid',
            'music_album' : 'American Teen',
            'music_image_link':  static('core/img/album2.jpg'),
        },
        {
            'music_name': 'In My Blood',
            'music_author': 'Shawn Mendes',
            'music_album' : 'Shawn Mendes',
            'music_image_link':  static('core/img/album3.jpg'),
        },
        {
            'music_name': 'One Last Time',
            'music_author': 'Ariana Grande',
            'music_album' : 'My Everything',
            'music_image_link':  static('core/img/album4.png'),
        },
        {
            'music_name': 'Hold Me Down',
            'music_author': 'Halsey',

dashboard/templates/dashboard/chat.html
<div class="chat-container">
            
    <div class="chat-window rounded-top">

        <button  class="btn chat-window-header m-0 p-0" data-toggle="collapse" href="#chatListBody" role="button"> 
            <p class="black-text">Chat</p>
        </button >

        <ul id="chatListBody" class="collapse list-group chat-list">

            {% for friend in view.get_chat_friends %}
                <a href"#" class="list-group-item chat-item" onclick='$(chatMessage).removeClass("hidden"); $(msgBox).removeClass("no-display")'>
                    <div class="row align-items-center">
                        <div class="col-auto pt-1">
                            <img src="{{ view.get_img }}" class="img-circle chat-img">
                        </div>
                        <div class="col">
                            <p class="black-text font-weight-bold row my-0"> {{ view.get_name }} </p>
                        </div>
                    </div>
                </a>
            {% endfor %}

            <div id="chatMessage" class="chat-message rounded-top hidden">

                <button  class="btn chat-window-header m-0 p-0" href="#" onclick='$(chatMessage).addClass("hidden"); $(msgBox).addClass("no-display")'> 
                    <p class="black-text">Voltar</p>
                </button >

                <div class="col">
                
                    {% for chat_menssage in view.get_chat_conversation %}
                        <div class="row py-1">

                            {% if chat_menssage.author.type == "sender" %}
                            <div class="col chat-sent-menssage mx-2 rounded">
                                <div class="row"> <!-- start row -->
                            {% else %}
                            <div class="col chat-received-menssage mx-2 rounded">
                                <div class="row"> <!-- start row -->
                                    <div class="col-auto pt-1 pr-0">
                                        <img src="{{ chat_menssage.author.img }}" class="img-circle chat-img">
                                    </div>
                            {% endif %}
                            
                                    <p class="col mx-1 black-text">
                                        {{chat_menssage.menssage}}
                                    </p>

                                    {% if chat_menssage.author.type == "sender" %}

                                        <div class="col-auto pt-1 pl-0">
                                            <img src="{{ chat_menssage.author.img }}" class="img-circle chat-img">
                                        </div>

                                    {% endif %}

                                </div> <!-- end row -->
                            </div>
                    
                        </div>
                    
                    {% endfor %}
                    
                </div>

            </div>

        </ul>

        <div id="msgBox" class="no-display chat-window-message-box m-0 p-0">

            <div class="input-group">
                <input type="text" class="form-control">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="button-post-comment"><i class="fas fa-comments black-icon"></i></button>
                </div>
            </div>
            
        </div>

    </div>
    

</div>

dashboard/templates/dashboard/content_footer.html
<div class="row">
    <div class="col px-1">
        <div class="input-group">
            <input type="text" class="form-control">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="button-post-comment"><i class="fas fa-comments black-icon"></i></button>
            </div>
        </div>
    </div>
    <div clas="col-auto">
        <button class="btn btn-outline-secondary" type="button" id="like" onclick="myFunction(this, {{content_piece.number_likes}})"><i id="heart"  class="far fa-heart red-icon col-auto px-1"></i><span id="number_likes">{{content_piece.number_likes}}</span></button>
    </div>
</div>

{% for comment in content_piece.comments %}

    <div class="row mt-2 ">

        <div class="col-auto pt-1 px-0 mx-1">
            <img src="{{ comment.img }}" class="img-circle small-profile-img">
        </div>

        <div class="col">

            <div class="row comment-box background-borded rounded">

                <div class="col mx-1">
                    <p class="row my-0 black-text"> {{ comment.text }} </p>
                </div>

                <div class="w-100" ></div>

                <div class="col"></div>
                <div class="col-auto mx-1 pt-1">
                    <p class="font-weight-bold row my-0 black-text"> {{ comment.author }} </p>
                </div>

            </div>

        </div>



    </div>


{% endfor %}

dashboard/templates/dashboard/content_piece.html
<div class="card my-1 content-card">
  <div class="card-header pt-1 pb-0 content-card-header">

    <div class="row">
      <div class="col-auto pt-1">
        <img src="{{ content_piece.author_img }}" class="img-circle small-profile-img">
      </div>
      <div class="col">
        <p class="black-text font-weight-bold row my-0"> {{ content_piece.author }} </p>
        <p class="black-text font-weight-light font-italic row my-0">{{ content_piece.date_time }}</p>
      </div>
    </div>

  </div>

  <div class="card-body content-card-body">

    <div class="row px-2">
    <p class="black-text card-text">{{ content_piece.menssage }}</p>
    </div>

    {% if content_piece.content_type is view.CONTENT_PLAYLIST %}
      {% include "dashboard/playlist_content.html" with content_piece=content_piece %}
    {% endif %}

    {% if content_piece.content_type is view.CONTENT_MUSIC %}
      {% include "dashboard/music_content.html" with content_piece=content_piece %}
    {% endif %}

  </div>

  <div class="card-footer text-muted content-card-footer">
    <div class="row align-items-center">
      <div class="col">

        {% include "dashboard/content_footer.html" with content_piece=content_piece%}

      </div>
    </div>
  </div>
</div>

dashboard/templates/dashboard/feed.html
{% extends 'core/base.html' %}

{% load static %}

{% block navbar %}
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link ml-5 selected" href="{% url 'dashboard:feed' %}">Dashboard</a>
      <a class="nav-item nav-link" href="{% url 'music:my_music' %}">Músicas</a>
    </div>
  </div>
{% endblock navbar %}

{% block css %}
  {{ block.super }}

  <link href="{% static 'dashboard/css/feed.css' %}" rel="stylesheet">

{% endblock css %}

{% block js %}
  {{ block.super }}

  <script type="text/javascript" src="{% static 'dashboard/js/feed.js' %}"></script>

{%  endblock js %}

{% block content %}

    <div class="row">

      <div class="col without-space">

        <!-- left panel -->

        {% include "dashboard/group_side.html" %}

      </div>


      <div class="col-6">

        <!-- feed section -->
        <div class="row my-2">
          <div class="col">

            <div class="card my-1 content-card">
              <div class="card-body content-card-body">
                <textarea class="post-text" placeholder="O que deseja postar?"></textarea>
              </div>
              <div class="card-footer text-muted content-card-footer">
                <div class="row align-items-center float-right">
                  <div class="col">
                    <button class="font-weight-bold btn playlist-button">📎</button>
                    <button class="font-weight-bold btn playlist-button">Compartilhar</button>
                  </div>
                </div>
              </div>
            </div>

        {% for content_piece in content  %}



              {% include "dashboard/content_piece.html" with content_piece=content_piece %}



        {% endfor %}

          </div>
        </div>

      </div>

      <div class="col">

        <!-- right panel -->

        {% include "dashboard/chat.html" %}


      </div>

    </div>

{% endblock content %}

dashboard/templates/dashboard/group.html
{% extends 'core/base.html' %}

{% load static %}

{% block navbar %}
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link ml-5 selected" href="{% url 'dashboard:feed' %}">Dashboard</a>
      <a class="nav-item nav-link" href="{% url 'music:my_music' %}">Músicas</a>
    </div>
  </div>
{% endblock navbar %}

{% block css %}
  {{ block.super }}

  <link href="{% static 'dashboard/css/feed.css' %}" rel="stylesheet">

{% endblock css %}

{% block js %}
  {{ block.super }}

  <script type="text/javascript" src="{% static 'dashboard/js/feed.js' %}"></script>

{%  endblock js %}

{% block content %}

    <div class="row">

      <div class="col without-space">

        <!-- left panel -->

        {% include "dashboard/group_side.html" %}

      </div>


      <div class="col-6">

        <!-- feed section -->

        <label class="label-ver-mais"><font size="8"> Rockeiros da FGA </font> </label>

        <div class="row my-2">
          <div class="col">
            <div class="card my-1 content-card">
              <div class="card-body content-card-body">
                <textarea class="post-text" placeholder="O que deseja postar?"></textarea>
              </div>
              <div class="card-footer text-muted content-card-footer">
                <div class="row align-items-center float-right">
                  <div class="col">
                    <button class="font-weight-bold btn playlist-button">📎</button>
                    <button class="font-weight-bold btn playlist-button">Compartilhar</button>
                  </div>
                </div>
              </div>
            </div>

        {% for content_piece in content  %}

              {% include "dashboard/content_piece.html" with content_piece=content_piece %}

        {% endfor %}

          </div>
        </div>

      </div>

      <div class="col">

        <!-- right panel -->

        {% include "dashboard/chat.html" %}


      </div>

    </div>

{% endblock content %}

dashboard/templates/dashboard/group_side.html
<div class="list-group list-size-top">
  <a href="{% url 'dashboard:feed' %}" class="list-group-item list-group-item-action black-background list-size">
    <font size="5">Feed</font>
  </a>
  <a class="list-group-item list-group-item-action black-background list-size">
    <font size="5">Grupos</font>
  </a>
  <a href="{% url 'dashboard:group' %}" class="list-group-item list-group-item-action gray-background list-size">🎸 Rockeiros da FGA</a>
  <a href="{% url 'dashboard:group' %}" class="list-group-item list-group-item-action gray-background list-size">🎷 Pop Rock Brasília</a>
  <a href="{% url 'dashboard:group' %}" class="list-group-item list-group-item-action gray-background list-size">🎹 Pagode Taguatinga</a>
  <a href="{% url 'dashboard:group' %}" class="list-group-item list-group-item-action gray-background list-size">🥁 Villa Mix Brasília</a>
  <label class="label-ver-mais">⇣ Ver Mais</label>
</div>

dashboard/templates/dashboard/music_content.html
{% load static %}
<script type="text/javascript" src="{% static 'dashboard/js/feed.js' %}"></script>
<audio id="myAudio">
        <source src="http://www.music.helsinki.fi/tmt/opetus/uusmedia/esim/a2002011001-e02.wav" type="audio/wav">
        Your browser does not support the audio element.
</audio>
 <div class="panel-body">
    <li class="list-group-item">
    <div class="row px-2 pt-1 align-items-center music-item">
        <a class="album-img col" href="#" onclick=playAudio(this) class="slider_info">
            <i id="play" class="fas fa-play fa-3x play-button"></i>
            <img class="img-fluid img-thumbnail" src={{content_piece.music.music_image_link}}>
        </a>
        <div class="col">
            {{content_piece.music.music_name}}
            <br>
            <p class="font-weight-light font-italic border-bottom album-info">
            {{content_piece.music.music_author}} - {{content_piece.music.music_album}}
            </p>
            <div class="row justify-content-end">
            <div class="col-auto">
              <a href="{% url 'music:my_music' %}"><button class="fas fa-plus-circle plus-button fa-2x"></button></a>
              <a href="{% url 'music:detail_music'%}"><button class="fas fa-external-link-square-alt info-button fa-2x"></button></a>
            </div>
            </div>
        </div>
    </div>
    </li>
</div>

dashboard/templates/dashboard/playlist_content.html
{% load static %}
<script type="text/javascript" src="{% static 'dashboard/js/feed.js' %}"></script>
<audio id="myAudio">
        <source src="http://www.music.helsinki.fi/tmt/opetus/uusmedia/esim/a2002011001-e02.wav" type="audio/wav">
        Your browser does not support the audio element.
</audio>
<div class="row justify-content-center">
    <div class="col mx-2">
    <div class="row">

        <ul class="list-group playlist-list-group col pb-0 mb-0">
            
            {% for music_playlist in content_piece.playlist %}
            <li class="list-group-item playlist-item">

                <div class="row mx-0 px-0 pt-1 music-item justify-content-between align-items-center">
                    <a class="col" href="#" onclick=playAudio2(this) class="slider_info">
                        <div class="row justify-content-center">
                        <div class="col-auto">
                        <i id="play" class="fas fa-play fa-2x small-play-button play-icon"></i>
                        <img class="img-thumbnail img-playlist img-play-icon" src={{music_playlist.music_image_link}}>
                        </div>
                        </div>
                    </a>

                    <div class="col album-info border-bottom">
                        {{music_playlist.music_name}}
                        <p class="black-text font-weight-light font-italic">
                            {{music_playlist.music_author}} - {{music_playlist.music_album}}
                        </p>
                    </div>

                    <div class="col-auto">
                      <a href="{% url 'music:my_music' %}"><button class="fas fa-plus-circle plus-button fa-2x"></button></a>
                      <a href="{% url 'music:detail_music'%}"><button class="fas fa-external-link-square-alt info-button fa-2x"></button></a>
                    </div>
                </div>

            </li>
            {% endfor %}

        </ul>
    </div>

    <div class="row playlist-info border rounded-bottom justify-content-between">
        <div class="col py-2 margin-little-top font-weight-bold ">
            Playlist: {{view.get_name_playlist}}
        </div>
        <div class="col py-2 margin-little-top font-weight-bold">
            Autor: {{view.get_name}}
        </div>
        <div class="col py-2">
            <a href="{% url 'music:detail_playlist' %}"><button class="float-right font-weight-bold btn playlist-button">Ir para playlist</button></a>
        </div>
    </div>
    </div>
</div>